version: '3.8'

services: 

  # Base de datos (PostgreSQL)
  postgres_db:
    image: postgres:17
    container_name: postgres_container
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./base_de_datos/web.sql:/docker-entrypoint-initdb.d/init.sql
  
  # Backend
  backend:
    build: ./servidor
    container_name: backend_container
    ports:
      - "5000:3000"
    env_file:
      - ./servidor/.env
    environment:
      - DB_HOST=postgres_db                     
    depends_on:
      - postgres_db
  
  # Frontend
  frontend:
    build: ./codigoProyecto
    container_name: frontend_container
    ports:
      - "8100:8100"
    environment:
      - VITE_API_URL=http://localhost:5000
    command: ionic serve --external --address 0.0.0.0 --port 8100
    depends_on:
      - backend

volumes:
  postgres_data:                              